name: SquadronsReloaded
version: 1.0.0
main: me.halfquark.squadronsreloaded.SquadronsReloaded
depend: [Movecraft]

commands:
   squadron:
      usage: /squadron [manoverboard|cruise|release|scuttle|formation|info|list]
      aliases: sq
      description: Squadron management
      permission: movecraft.squadron