carriedTypes:
  - Airskiff
carrierTypes:
  - Airship
  - elevator
needsCarrier: true
manoverboardTime: 30000
tpToNewLead: true
turnTicks: 2
squadMaxSize: 12
squadMaxSizeCarrierMultiplier: 0.0
squadMaxDisplacement: 12000
squadMaxDisplacementCarrierMultiplier: 0.0
formationRoundDistance: 0.0
formationSpeedMultiplier: 0.5
squadronPilotTool: COMPASS
blockCountOverride: true
syncedSigns:
  - LaunchTorpedo