carriedTypes:
  - Airskiff
carrierTypes:
  - Airship
  - elevator
pilotCheckTicks: 40
manoverboardTime: 30000
turnTicks: 2
squadMaxSize: 12
squadMaxSizeCarrierMultiplier: 0.0
squadMaxDisplacement: 12000
squadMaxDisplacementCarrierMultiplier: 0.0
formationRoundDistance: 3.0
syncedSigns:
  - LaunchTorpedo